# filter 过滤不存在的节点将会自动过滤
# { name: "hk", filter: '香港' }
filters:
  - { name: "hk", filter: '香港' }
  - { name: "tw", filter: '台湾' }
  - { name: "jp", filter: '日本' }
  - { name: "sg", filter: '新加坡|狮城' }
  - { name: "us", filter: '美国' }
  - { name: "kr", filter: 'Korea|韩国' }


# example: { group: { name: "YouTube", type: url-test, proxies: [ "Proxy" ], url: 'http://www.gstatic.com/generate_204', interval: 300 }, rm_airports: true }
groups:
  - { group: { name: "Apple", type: select, proxies: [ "DIRECT", "Proxy" ] }, use_filters: [ "us","jp" ] }
  - { group: { name: "Amazon", type: select, proxies: [ "Proxy" ] }, use_filters: [ "us","sg","hk" ] }
  - { group: { name: "Google", type: select, proxies: [ "Proxy" ] }, use_filters: [ "us","sg","hk" ] }
  - { group: { name: "YouTube", type: select, proxies: [ "Proxy" ] }, use_filters: [ "tw","hk" ] }
  - { group: { name: "Netflix", type: select, proxies: [ "Proxy" ] }, use_filters: [ "tw","hk" ] }
  - { group: { name: "Telegram", type: select, proxies: [ "Proxy" ] }, use_filters: [ "tw","hk" ] }
  - { group: { name: "Twitter", type: select, proxies: [ "Proxy" ] }, use_filters: [ "tw","hk" ] }
  - { group: { name: "TikTok", type: select }, use_filters: [ "tw","us","sg" ], rm_airports: true }
  - { group: { name: "OpenAI", type: select, proxies: [ "Proxy" ] }, use_filters: [ "jp","us","sg" ] }